# Model configuration
model_type: "RandomForestClassifier"
default_params:
  random_state: 42
  class_weight: "balanced"  # Important for imbalanced SFP datasets
  n_jobs: -1

# HPO search space - CONTINUOUS INTERVALS
search_space:
  # Number of estimators (log-uniform integer)
  n_estimators:
    type: "int_log_uniform"
    min_value: 10
    max_value: 1000
  
  # Maximum depth (uniform integer, with None option)
  max_depth:
    type: "int_uniform_with_none"
    min_value: 3
    max_value: 50
    none_probability: 0.2  # 20% chance to sample None
  
  # Minimum samples split (uniform integer + continuous)
  min_samples_split:
    type: "int_uniform"
    min_value: 2
    max_value: 20
  
  # Minimum samples leaf (uniform integer + continuous)
  min_samples_leaf:
    type: "int_uniform"
    min_value: 1
    max_value: 20
  
  # Maximum features (uniform continuous)
  max_features:
    type: "uniform"
    min_value: 0.1
    max_value: 1.0
  
  # Bootstrap (categorical)
  bootstrap:
    type: "categorical"
    choices: [true, false]
  
  # Minimum impurity decrease (uniform continuous)
  min_impurity_decrease:
    type: "uniform"
    min_value: 0.0
    max_value: 0.2
  
  # Maximum leaf nodes (uniform integer with None)
  max_leaf_nodes:
    type: "int_uniform_with_none"
    min_value: 10
    max_value: 1000
    none_probability: 0.7  # 70% chance to sample None


