# Project metadata
project_name: "SFP_SSA"
version: "1.0.0"
random_seed: 42

# Paths
data_dir: "data"
results_dir: "results"
logs_dir: "experiments/logs"

# Experiment settings
n_jobs: 2  # Use 2 CPU cores
verbose: 1
